version: '3'
services:
  # API Service
  api:
    image: node:6.17.1
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    environment:
      - PORT=${API_PORT}
      - DB=${API_DB}
    depends_on:
      - db

  # Web Service
  web:
    image: node:6.17.1
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
    environment:
      - PORT=${WEB_PORT}
      - API_HOST=${API_HOST}

  # PostgreSQL Database
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:


