version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
db:
    image: 'postgres'
    ports:
      - '4444:5432'
    environment:
      POSTGRES_USER: 'database'
      POSTGRES_PASSWORD: '557768'

